package com.littleone.littleone_web.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Temp")
public class Temp {
	private int infant_idx;
	private Long date_time;
	private float temp;
	private String memo;	// 필수 x
	private String memo_time;	// 필수 x. 사용자가 오늘날짜에서 시간만 설정

	@DynamoDBHashKey(attributeName="infant_idx") 
	//@DynamoDBAutoGeneratedKey
	public int getInfant_idx() {
		return infant_idx;
	}
	public void setInfant_idx(int infant_idx) {
		this.infant_idx = infant_idx;
	}
	
	@DynamoDBRangeKey(attributeName="date_time")
	public Long getDate_time() {
		return date_time;
	}
	public void setDate_time(Long date_time) {
		this.date_time = date_time;
	}
	
	@DynamoDBAttribute(attributeName="temp")
	public float getTemp() {
		return temp;
	}
	public void setTemp(float temp) {
		this.temp = temp;
	}
	
	@DynamoDBAttribute(attributeName="memo")
	public String getMemo() {
		return memo;
	}
	
	public void setMemo(String memo) {
		this.memo = memo;
	}
	
	@DynamoDBAttribute(attributeName="memo_time")
	public String getMemo_time() {
		return memo_time;
	}
	public void setMemo_time(String memo_time) {
		this.memo_time = memo_time;
	}
	
	public Temp() {
		super();
	}
}
